

insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (62, 15, 8, 15, 4, 11, 4296, 9, 0.03, 1712, 4, 11818, 7697, 609);

insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (31, 7, 6, 12, 20, 15, 4592, 7, 0.06, 391, 2, 10028, 3365, 644);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (60, 3, 6, 2, 14, 18, 3033, 8, 0.08, 530, 1, 9613, 11587, 736);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (61, 11, 5, 5, 20, 16, 3423, 7, 0.08, 1854, 1, 12626, 9118, 521);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (33, 12, 1, 20, 5, 15, 3216, 16, 0.07, 847, 2, 6477, 9655, 364);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (51, 8, 9, 4, 13, 6, 3362, 11, 0.09, 857, 1, 7665, 11688, 337);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (48, 14, 4, 19, 1, 14, 5957, 11, 0.08, 1223, 4, 6819, 13950, 937);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (77, 6, 9, 12, 15, 7, 4838, 12, 0.02, 1628, 3, 11195, 14650, 914);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (21, 12, 6, 16, 4, 16, 5518, 20, 0.04, 1549, 2, 10374, 17876, 121);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (35, 1, 1, 12, 10, 15, 2928, 20, 0.06, 154, 1, 6924, 4211, 482);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (30, 12, 6, 13, 6, 17, 4197, 19, 0.03, 1730, 4, 18502, 2701, 588);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (37, 5, 7, 9, 10, 3, 4570, 8, 0.03, 541, 3, 7441, 16349, 931);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (46, 14, 5, 15, 16, 16, 3891, 7, 0.05, 1361, 3, 17934, 8815, 742);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (46, 12, 1, 13, 2, 17, 3533, 5, 0.02, 654, 1, 16845, 14264, 772);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (87, 7, 3, 12, 13, 12, 5405, 16, 0.06, 232, 1, 13716, 8028, 74);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (5, 13, 7, 14, 11, 17, 3212, 6, 0.02, 583, 4, 11251, 1380, 404);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (88, 18, 6, 6, 2, 15, 3790, 5, 0.03, 1266, 3, 11474, 3656, 85);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (21, 7, 4, 8, 12, 5, 5315, 19, 0.06, 789, 4, 8091, 8663, 630);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (92, 2, 8, 20, 19, 16, 5189, 12, 0.08, 1581, 4, 2657, 1662, 4);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (33, 7, 5, 13, 14, 5, 2882, 1, 0.08, 1712, 1, 19716, 14424, 88);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (48, 1, 1, 9, 10, 19, 4029, 17, 0.02, 1576, 4, 12841, 6465, 989);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (63, 15, 6, 17, 2, 5, 4936, 17, 0.06, 928, 3, 7525, 3644, 863);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (89, 5, 6, 10, 20, 6, 5960, 20, 0.06, 1079, 2, 8037, 15399, 637);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (91, 3, 6, 13, 13, 8, 5949, 8, 0.05, 1118, 1, 10741, 15827, 465);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (89, 18, 7, 12, 3, 17, 3338, 14, 0.04, 1938, 1, 5502, 6224, 22);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (48, 14, 3, 3, 8, 9, 3556, 9, 0.03, 560, 1, 9567, 13706, 462);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (49, 20, 1, 20, 13, 1, 4387, 5, 0.06, 993, 4, 18181, 5455, 73);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (42, 4, 7, 12, 13, 16, 3683, 6, 0.05, 810, 2, 15329, 7344, 812);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (60, 11, 9, 9, 11, 8, 3245, 13, 0.07, 333, 4, 2368, 4572, 668);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (70, 1, 8, 4, 15, 12, 5216, 15, 0.07, 1652, 2, 19726, 3355, 704);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (50, 14, 4, 19, 4, 12, 4011, 11, 0.03, 425, 3, 3299, 18319, 299);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (10, 7, 7, 15, 13, 4, 5984, 3, 0.07, 103, 1, 11376, 9058, 37);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (70, 12, 6, 20, 12, 13, 5606, 20, 0.05, 1601, 2, 587, 11864, 91);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (85, 13, 6, 6, 14, 5, 3756, 6, 0.01, 765, 1, 19935, 6135, 494);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (15, 4, 9, 5, 4, 18, 3272, 8, 0.06, 609, 1, 12420, 16164, 602);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (58, 6, 5, 9, 17, 12, 4071, 1, 0.05, 1797, 1, 10017, 10767, 58);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (50, 1, 4, 12, 15, 1, 2857, 20, 0.02, 1147, 1, 3171, 12481, 100);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (15, 7, 4, 11, 14, 17, 3939, 17, 0.05, 1492, 2, 18692, 13912, 525);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (97, 9, 8, 7, 16, 14, 4029, 20, 0.04, 1779, 1, 7025, 753, 93);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (39, 8, 4, 3, 14, 13, 3773, 10, 0.03, 1994, 2, 10790, 6345, 733);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (61, 5, 8, 4, 19, 19, 5609, 4, 0.08, 1546, 2, 7178, 17026, 744);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (73, 17, 2, 11, 3, 18, 4125, 6, 0.02, 1771, 3, 12698, 3676, 717);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (43, 14, 8, 11, 7, 15, 5540, 1, 0.02, 274, 2, 11458, 7275, 940);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (56, 4, 2, 7, 13, 3, 3684, 10, 0.07, 1480, 3, 15982, 11087, 170);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (66, 18, 4, 17, 9, 18, 4569, 5, 0.08, 753, 3, 8115, 8652, 708);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (40, 9, 3, 4, 3, 6, 4167, 7, 0.08, 889, 1, 9600, 16272, 990);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (24, 3, 9, 18, 17, 19, 4578, 6, 0.04, 1315, 4, 16761, 14048, 548);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (29, 5, 5, 18, 18, 12, 2858, 13, 0.05, 1968, 1, 18610, 3487, 737);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (17, 18, 6, 9, 10, 6, 4867, 15, 0.02, 1932, 4, 7106, 15719, 628);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (59, 10, 9, 17, 1, 9, 5464, 20, 0.06, 1945, 1, 5384, 4208, 117);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (83, 8, 5, 3, 20, 13, 5067, 14, 0.07, 1660, 4, 5394, 19097, 944);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (37, 8, 2, 18, 11, 10, 3841, 2, 0.05, 988, 3, 1785, 18276, 67);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (25, 10, 6, 6, 1, 3, 4226, 7, 0.06, 1562, 2, 12894, 6459, 191);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (44, 9, 6, 13, 18, 12, 4539, 17, 0.05, 1193, 2, 8568, 5898, 89);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (95, 19, 7, 20, 13, 10, 4320, 4, 0.05, 451, 3, 13630, 17038, 639);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (22, 7, 5, 9, 10, 4, 4800, 13, 0.06, 1294, 1, 6897, 2915, 770);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (81, 1, 7, 20, 10, 1, 3329, 19, 0.02, 955, 3, 11059, 8445, 421);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (91, 1, 7, 12, 20, 6, 3789, 7, 0.04, 1735, 4, 10047, 8816, 388);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (62, 3, 7, 14, 6, 3, 5988, 19, 0.02, 415, 3, 7350, 1089, 147);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (11, 14, 6, 15, 17, 19, 3883, 6, 0.08, 1436, 2, 12398, 8363, 861);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (38, 3, 2, 7, 19, 8, 4906, 7, 0.07, 384, 3, 15341, 2264, 662);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (34, 3, 6, 17, 1, 1, 3546, 15, 0.05, 458, 3, 9472, 10813, 244);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (31, 10, 9, 18, 16, 18, 5365, 19, 0.06, 432, 1, 2256, 17389, 204);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (97, 16, 7, 12, 10, 7, 2921, 10, 0.08, 1315, 3, 3683, 8577, 959);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (53, 12, 7, 15, 18, 14, 5557, 4, 0.06, 806, 1, 9490, 9726, 704);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (12, 6, 2, 18, 14, 17, 2813, 8, 0.01, 775, 1, 14487, 1889, 484);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (67, 5, 6, 6, 5, 12, 4826, 10, 0.09, 1991, 3, 10910, 1564, 178);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (54, 13, 2, 18, 1, 6, 5389, 15, 0.04, 1502, 3, 17748, 13817, 334);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (72, 16, 4, 17, 13, 13, 5288, 14, 0.06, 488, 2, 1764, 16991, 919);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (93, 8, 9, 10, 5, 11, 4745, 4, 0.08, 1472, 1, 19579, 8529, 299);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (12, 20, 6, 19, 4, 11, 4066, 1, 0.02, 1238, 2, 1119, 17479, 63);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (12, 4, 1, 17, 6, 3, 5638, 17, 0.08, 248, 4, 8024, 2287, 892);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (93, 1, 7, 7, 9, 2, 4537, 15, 0.08, 100, 3, 14611, 16977, 792);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (53, 1, 6, 10, 5, 14, 3221, 14, 0.06, 1746, 1, 17031, 803, 348);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (51, 17, 2, 4, 10, 5, 5407, 11, 0.02, 144, 2, 12705, 15499, 624);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (35, 8, 4, 7, 12, 19, 5429, 20, 0.05, 317, 3, 2609, 8170, 8);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (71, 8, 9, 13, 20, 2, 5709, 6, 0.07, 1966, 4, 634, 6511, 272);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (33, 9, 6, 5, 5, 9, 3389, 7, 0.07, 1381, 1, 15749, 10869, 941);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (30, 7, 3, 2, 2, 14, 4124, 13, 0.08, 1605, 1, 16420, 7773, 634);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (43, 20, 7, 5, 11, 6, 3344, 10, 0.02, 1480, 3, 8801, 8598, 596);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (21, 17, 5, 13, 14, 13, 5336, 1, 0.08, 159, 2, 4816, 19880, 367);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (34, 7, 9, 17, 16, 4, 5438, 4, 0.03, 1688, 3, 4358, 17315, 93);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (24, 12, 1, 2, 19, 5, 2583, 8, 0.06, 305, 1, 9977, 6533, 618);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (7, 18, 6, 20, 18, 11, 4144, 18, 0.02, 1635, 1, 13709, 14854, 29);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (83, 3, 7, 5, 20, 8, 5409, 16, 0.05, 1135, 2, 14169, 13748, 813);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (82, 5, 1, 10, 6, 17, 5358, 2, 0.05, 1606, 3, 6338, 11919, 1000);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (44, 9, 5, 11, 4, 9, 5331, 16, 0.05, 1018, 1, 11112, 18506, 759);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (81, 13, 3, 19, 16, 16, 5491, 14, 0.06, 1534, 3, 9205, 12692, 890);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (32, 1, 1, 4, 17, 6, 2684, 11, 0.07, 1099, 4, 4298, 9104, 436);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (15, 11, 4, 11, 9, 12, 5017, 12, 0.06, 1931, 3, 8409, 7940, 620);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (12, 11, 5, 9, 15, 16, 4156, 18, 0.09, 1913, 4, 6977, 11578, 121);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (7, 12, 2, 6, 18, 18, 5534, 4, 0.03, 1450, 4, 2221, 5999, 688);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (28, 1, 7, 9, 8, 13, 2978, 1, 0.08, 557, 3, 5977, 16328, 997);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (39, 13, 8, 8, 16, 1, 4301, 6, 0.02, 386, 1, 14585, 12821, 87);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (76, 19, 8, 3, 15, 7, 3184, 8, 0.03, 1928, 1, 6086, 9017, 741);
insert into flight_activities  (Date_key, Time_key , Passenger_key , Passenger_profile_key , Flight_key, Fair_base_key , Ticket_number , Aircraft_key , Airport_tax , Baggages_charges , Channel_key , Fair_base_revenue , Upgrade_fees , Earned_miles ) values (60, 4, 7, 3, 13, 18, 5778, 13, 0.05, 1548, 4, 6138, 1489, 630);


-------------------------------------------------------------------------------------

insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (9, 7, 7, 6);

insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (6, 8, 95, 3);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (8, 1, 20, 9);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (1, 3, 84, 10);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (4, 10, 86, 4);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (5, 3, 32, 3);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (4, 6, 28, 6);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (1, 4, 38, 7);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (2, 10, 36, 7);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (5, 7, 66, 10);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (2, 2, 14, 6);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (4, 7, 10, 3);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (3, 10, 48, 1);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (1, 9, 77, 7);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (5, 6, 7, 2);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (4, 8, 98, 8);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (9, 2, 99, 2);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (6, 3, 6, 6);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (8, 10, 88, 5);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (8, 5, 61, 4);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (1, 8, 63, 1);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (5, 8, 38, 3);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (7, 5, 16, 5);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (7, 1, 10, 4);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (8, 4, 91, 4);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (1, 7, 55, 6);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (4, 9, 53, 4);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (2, 8, 48, 3);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (3, 1, 25, 5);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (2, 2, 67, 9);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (1, 7, 83, 2);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (6, 3, 43, 4);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (7, 9, 13, 5);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (6, 4, 100, 6);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (3, 4, 16, 3);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (3, 10, 58, 9);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (7, 3, 5, 4);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (2, 5, 68, 3);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (5, 1, 27, 5);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (5, 8, 36, 9);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (9, 10, 100, 5);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (7, 2, 83, 2);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (4, 9, 51, 5);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (7, 8, 71, 2);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (9, 1, 72, 10);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (1, 3, 21, 7);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (6, 8, 69, 4);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (7, 3, 49, 2);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (9, 7, 62, 2);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (7, 6, 53, 3);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (7, 3, 9, 9);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (1, 8, 57, 7);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (7, 2, 81, 1);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (1, 4, 75, 4);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (5, 10, 4, 4);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (2, 7, 20, 4);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (2, 4, 52, 6);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (7, 10, 13, 2);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (3, 7, 61, 8);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (1, 9, 49, 1);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (7, 10, 96, 2);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (7, 5, 94, 9);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (1, 1, 59, 5);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (1, 2, 83, 10);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (6, 10, 20, 9);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (4, 10, 78, 10);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (7, 10, 15, 5);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (8, 1, 53, 6);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (9, 1, 88, 3);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (6, 8, 99, 8);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (2, 4, 69, 1);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (6, 7, 56, 5);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (2, 8, 56, 5);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (1, 8, 61, 2);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (2, 6, 82, 9);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (2, 6, 48, 10);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (3, 6, 23, 8);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (9, 8, 90, 10);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (9, 6, 90, 8);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (7, 1, 91, 10);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (3, 8, 38, 6);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (5, 7, 31, 10);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (8, 6, 82, 2);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (2, 5, 95, 2);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (4, 2, 30, 9);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (1, 6, 13, 2);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (6, 1, 74, 2);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (5, 8, 63, 3);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (3, 6, 43, 9);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (6, 10, 87, 1);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (2, 6, 45, 8);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (2, 8, 81, 6);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (3, 4, 68, 9);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (7, 5, 51, 9);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (7, 8, 55, 9);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (7, 7, 88, 2);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (8, 9, 97, 1);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (5, 4, 60, 3);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (4, 7, 70, 3);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (3, 1, 24, 9);
insert into frequent_promotions  (passenger_profile_key , promotion_key , date_key , promotion_count ) values (6, 5, 39, 2);



---------------------------------------------Over_Night-------------------------------

insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (38, 50, 86, 54, 20, 5, 4881, 13, 4);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (85, 51, 15, 91, 6, 17, 2754, 9, 4);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (91, 56, 61, 60, 5, 2, 4436, 9, 3);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (7, 37, 98, 29, 16, 15, 4869, 9, 1);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (93, 49, 9, 69, 20, 17, 5336, 4, 2);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (60, 92, 34, 85, 17, 14, 3730, 13, 9);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (96, 25, 17, 82, 11, 1, 2871, 10, 2);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (13, 92, 71, 85, 14, 6, 4361, 4, 4);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (13, 6, 8, 44, 10, 13, 3585, 10, 1);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (83, 75, 22, 85, 5, 9, 4350, 10, 2);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (24, 25, 11, 52, 20, 7, 2791, 12, 2);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (99, 97, 87, 68, 8, 1, 4423, 20, 5);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (64, 100, 95, 4, 12, 18, 5096, 14, 1);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (55, 71, 8, 74, 5, 3, 3976, 12, 9);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (100, 61, 37, 62, 12, 16, 2708, 3, 6);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (39, 95, 67, 76, 12, 1, 5053, 3, 3);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (59, 62, 11, 8, 4, 12, 4676, 4, 6);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (96, 39, 5, 46, 7, 12, 3848, 18, 5);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (62, 6, 33, 56, 7, 14, 4626, 8, 3);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (50, 95, 54, 40, 1, 13, 4158, 7, 8);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (34, 7, 36, 69, 12, 9, 4697, 12, 6);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (42, 72, 65, 88, 9, 11, 3381, 2, 2);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (76, 54, 62, 6, 5, 6, 4360, 3, 8);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (53, 41, 26, 28, 15, 4, 4730, 12, 2);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (82, 90, 36, 14, 7, 19, 2828, 8, 3);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (82, 43, 20, 32, 3, 16, 4594, 20, 3);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (82, 77, 14, 62, 14, 13, 4801, 9, 5);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (87, 77, 59, 58, 7, 14, 2883, 20, 6);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (99, 77, 96, 15, 4, 7, 5112, 14, 6);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (9, 17, 7, 81, 2, 19, 2823, 14, 2);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (91, 18, 61, 17, 11, 14, 5355, 13, 8);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (16, 61, 12, 20, 7, 9, 3852, 4, 7);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (27, 29, 49, 37, 14, 10, 4166, 16, 4);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (33, 70, 73, 77, 6, 18, 3247, 15, 9);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (72, 41, 44, 39, 18, 5, 4301, 5, 3);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (25, 79, 65, 50, 4, 10, 5346, 7, 5);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (49, 35, 11, 19, 3, 18, 5706, 20, 7);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (67, 92, 5, 20, 19, 15, 4504, 11, 3);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (52, 73, 15, 45, 4, 3, 4894, 6, 5);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (59, 13, 37, 96, 12, 17, 5621, 11, 4);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (70, 31, 37, 44, 16, 6, 4998, 16, 1);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (91, 9, 74, 74, 16, 12, 4910, 16, 2);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (20, 85, 80, 91, 1, 2, 4552, 19, 3);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (43, 57, 4, 63, 16, 12, 5406, 18, 7);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (36, 100, 97, 59, 20, 18, 4276, 8, 6);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (85, 13, 91, 20, 16, 3, 5318, 7, 5);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (77, 24, 47, 39, 4, 17, 5442, 7, 6);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (28, 35, 86, 42, 13, 13, 5816, 2, 7);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (31, 45, 46, 48, 19, 5, 4444, 7, 6);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (26, 8, 65, 43, 8, 7, 5912, 16, 3);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (44, 80, 87, 45, 8, 8, 5493, 6, 7);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (45, 61, 31, 62, 2, 15, 4126, 11, 8);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (93, 65, 68, 74, 4, 9, 5206, 2, 7);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (91, 22, 64, 94, 4, 17, 4196, 18, 1);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (81, 37, 31, 61, 12, 11, 3412, 18, 6);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (9, 34, 55, 76, 14, 7, 4144, 18, 6);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (73, 37, 30, 13, 11, 4, 2575, 4, 6);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (75, 82, 98, 98, 12, 18, 2969, 7, 3);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (8, 19, 8, 59, 17, 10, 5837, 15, 5);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (45, 10, 81, 78, 14, 1, 3936, 18, 1);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (5, 92, 80, 76, 18, 8, 2620, 11, 8);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (37, 41, 65, 32, 10, 17, 3054, 10, 6);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (96, 6, 57, 82, 19, 17, 5218, 7, 9);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (8, 74, 73, 58, 14, 5, 4524, 19, 4);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (53, 16, 87, 62, 17, 13, 5190, 4, 1);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (20, 30, 50, 72, 2, 16, 2973, 13, 7);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (73, 43, 45, 35, 2, 15, 5850, 13, 8);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (67, 68, 28, 76, 11, 1, 3130, 4, 9);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (32, 7, 69, 57, 3, 10, 5121, 8, 1);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (45, 21, 15, 48, 18, 13, 5789, 8, 8);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (85, 18, 82, 30, 12, 6, 3504, 10, 4);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (72, 27, 4, 79, 18, 17, 5897, 9, 6);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (10, 35, 76, 11, 10, 13, 4334, 9, 5);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (16, 41, 12, 37, 9, 2, 5931, 1, 9);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (12, 45, 95, 65, 14, 17, 2620, 10, 8);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (64, 12, 34, 15, 16, 2, 4875, 3, 6);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (74, 46, 39, 37, 10, 10, 3580, 10, 8);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (23, 27, 7, 11, 15, 16, 4855, 12, 9);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (51, 98, 52, 39, 1, 3, 2772, 13, 2);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (58, 77, 23, 23, 9, 2, 4779, 18, 6);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (48, 19, 81, 44, 8, 16, 3945, 17, 8);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (45, 85, 13, 18, 1, 2, 5895, 19, 6);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (71, 78, 56, 100, 13, 8, 4632, 10, 9);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (14, 39, 91, 67, 11, 17, 3444, 13, 5);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (79, 47, 66, 69, 8, 8, 3223, 3, 2);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (32, 23, 52, 62, 6, 3, 5086, 5, 9);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (66, 74, 64, 31, 6, 12, 3525, 4, 1);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (6, 13, 41, 53, 11, 3, 3641, 1, 7);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (39, 64, 6, 40, 14, 9, 4465, 10, 6);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (56, 57, 62, 91, 13, 9, 3269, 6, 5);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (80, 7, 22, 6, 12, 2, 4150, 5, 9);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (28, 6, 36, 16, 15, 5, 5791, 19, 7);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (6, 14, 98, 86, 8, 8, 5665, 3, 3);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (89, 16, 57, 18, 6, 10, 2628, 1, 3);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (23, 46, 94, 46, 5, 15, 5225, 1, 8);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (34, 98, 77, 21, 1, 2, 4576, 7, 4);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (28, 69, 85, 41, 1, 9, 4439, 15, 4);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (7, 83, 34, 16, 14, 9, 4432, 20, 9);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (80, 91, 67, 80, 2, 3, 2614, 1, 7);
insert into Over_Night_Stay_New (date_Key , date_of_arrival , date_of_departure , date_of_reservation , flight_key , hotel_key , Number_of_nights , room_charge , passenger_key ) values (5, 45, 19, 32, 8, 14, 4260, 12, 3);


-----------------------------------------------------

insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (21, 8, 13, 29, 4);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (44, 1, 1, 18, 2);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (52, 6, 4, 18, 8);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (65, 2, 8, 10, 4);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (91, 3, 12, 39, 3);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (28, 8, 10, 6, 2);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (20, 5, 9, 32, 10);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (49, 1, 1, 31, 5);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (34, 7, 10, 7, 4);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (29, 2, 19, 19, 10);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (71, 7, 8, 19, 10);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (92, 1, 11, 11, 9);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (58, 4, 2, 21, 3);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (80, 8, 14, 7, 5);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (42, 3, 19, 3, 1);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (51, 9, 12, 35, 9);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (51, 6, 2, 22, 5);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (67, 8, 16, 13, 2);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (46, 6, 7, 14, 4);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (6, 6, 18, 34, 9);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (47, 6, 20, 6, 8);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (15, 1, 11, 30, 2);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (28, 5, 9, 31, 9);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (76, 2, 11, 35, 5);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (94, 9, 9, 4, 10);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (67, 6, 13, 34, 2);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (65, 2, 7, 3, 3);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (43, 8, 6, 30, 1);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (47, 9, 20, 22, 7);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (9, 1, 10, 12, 5);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (43, 2, 19, 12, 5);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (74, 2, 15, 25, 7);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (51, 8, 17, 24, 8);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (31, 3, 8, 9, 9);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (46, 3, 1, 28, 9);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (85, 9, 14, 35, 5);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (43, 7, 7, 18, 2);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (32, 9, 12, 10, 4);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (47, 4, 12, 35, 10);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (20, 3, 11, 6, 7);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (89, 2, 9, 26, 4);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (99, 2, 1, 8, 7);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (40, 5, 14, 34, 8);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (15, 4, 5, 36, 6);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (54, 2, 2, 11, 5);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (33, 4, 19, 34, 2);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (89, 4, 4, 2, 5);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (94, 2, 5, 14, 7);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (20, 9, 18, 20, 7);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (68, 8, 19, 15, 3);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (89, 4, 3, 35, 4);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (100, 6, 5, 8, 9);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (18, 4, 14, 29, 5);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (55, 2, 18, 13, 9);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (82, 4, 14, 16, 10);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (75, 5, 12, 7, 4);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (95, 8, 19, 29, 1);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (44, 9, 10, 3, 3);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (27, 6, 3, 15, 3);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (16, 7, 10, 3, 2);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (90, 9, 15, 3, 8);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (13, 9, 5, 16, 1);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (99, 5, 14, 13, 3);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (64, 3, 15, 25, 5);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (78, 5, 13, 6, 5);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (30, 6, 3, 30, 1);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (91, 4, 17, 19, 6);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (26, 2, 17, 39, 4);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (18, 7, 13, 11, 9);
insert into customer_care  (date_Key , passenger_key , flight_key , Interaction_ID , rate ) values (68, 3, 7, 31, 9);